baseURL = "https://www.sigmobile.org/mobisys/2025/"
languageCode = "en-us"
title = "ACM MobiSys 2025"
enableRobotsTXT = true

# Disable categories and tags
[Taxonomies]

# Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Calls"
    url = "#"
    weight = 2
  [[menu.main]]
    name = "Call For Papers"
    url = "/call_for_papers/"
    parent = "Calls"
    weight = 1
  [[menu.main]]
    name = "Call For Posters"
    url = "/call_for_posters/"
    parent = "Calls"
    weight = 2
  [[menu.main]]
    name = "Call For Workshops"
    url = "/call_for_workshops/"
    parent = "Calls"
    weight = 3
  [[menu.main]]
    name = "Call For N<sup>2</sup>Women"
    url = "/n2women/"
    parent = "Calls"
    weight = 4
  [[menu.main]]
    name = "Call For Demos"
    url = "/call_for_demos/"
    parent = "Calls"
    weight = 5
  [[menu.main]]
    name = "Accepted"
    url = "#"
    weight = 3
  [[menu.main]]
    name = "Accepted Workshops"
    url = "/accepted_workshops/"
    parent = "Accepted"
    weight = 1
  # [[menu.main]]
  #   name = "Program"
  #   url = "#"
  #   weight = 4
  [[menu.main]]
    name = "Attending"
    url = "#"
    weight = 5
  [[menu.main]]
    name = "Venue"
    url = "/venue/"
    parent = "Attending"
    weight = 1
  [[menu.main]]
    name = "Committees"
    url = "#"
    weight = 6
  [[menu.main]]
    name = "Organizing Committee"
    url = "/organizing_committee/"
    parent = "Committees"
    weight = 1
  [[menu.main]]
    name = "Program Committee"
    url = "/program_committee/"
    parent = "Committees"
    weight = 2
  [[menu.main]]
    name = "PC Self Nomination"
    url = "/pc_self_nomination/"
    parent = "Committees"
    weight = 3
  [[menu.main]]
    name = "Sponsorship"
    url = "/sponsorship/"
    weight = 7
